version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: igraal
    ports:
      - '3306'

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_ROOT_PASSWORD: password
      PMA_DATABASE: igraal
    ports:
      - '8081:80'
    depends_on:
      - database
      
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
